
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__policy_proxy_h__PROXY_MARSHAL_H
#define __dbusxx__policy_proxy_h__PROXY_MARSHAL_H

#include <dbus-c++-1/dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace freedesktop {
namespace keti {
namespace bmc {

class policy_proxy
: public ::DBus::InterfaceProxy
{
public:

    policy_proxy()
    : ::DBus::InterfaceProxy("org.freedesktop.keti.bmc.policy")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    ::DBus::Struct< std::string, int32_t, int32_t, int32_t, int32_t, std::string > getFan(const std::string& FanName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << FanName;
        call.member("getFan");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< std::string, int32_t, int32_t, int32_t, int32_t, std::string > argout;
        ri >> argout;
        return argout;
    }

    ::DBus::Struct< int32_t, std::string > getFanTargetPolicy(const std::string& FanPolicyName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << FanPolicyName;
        call.member("getFanTargetPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< int32_t, std::string > argout;
        ri >> argout;
        return argout;
    }

    int32_t setFan(const std::string& FanName, const std::string& FanName_string)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << FanName;
        wi << FanName_string;
        call.member("setFan");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    ::DBus::Struct< std::string, std::string, std::string, int32_t, std::string, std::string > getFanPolicy(const std::string& policyName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        call.member("getFanPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< std::string, std::string, std::string, int32_t, std::string, std::string > argout;
        ri >> argout;
        return argout;
    }

    int32_t setFanPolicyString(const std::string& policyName, const std::string& attribute, const std::string& attributeName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << attribute;
        wi << attributeName;
        call.member("setFanPolicyString");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t setFanPolicyInt(const std::string& policyName, const std::string& attribute, const int32_t& attributeValue)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << attribute;
        wi << attributeValue;
        call.member("setFanPolicyInt");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t createFanPolicy(const std::string& description, const std::string& policyName, const std::string& algorithm, const std::string& temperatureSource, const int32_t& desiredTemperature)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << description;
        wi << policyName;
        wi << algorithm;
        wi << temperatureSource;
        wi << desiredTemperature;
        call.member("createFanPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t deleteFanPolicy(const std::string& policyName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        call.member("deleteFanPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    ::DBus::Struct< std::string, std::string, std::string, int32_t, int32_t > getCPUPolicy(const std::string& policyName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        call.member("getCPUPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< std::string, std::string, std::string, int32_t, int32_t > argout;
        ri >> argout;
        return argout;
    }

    int32_t setCPUPolicyString(const std::string& policyName, const std::string& attribute, const std::string& attributeName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << attribute;
        wi << attributeName;
        call.member("setCPUPolicyString");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t setCPUPolicyInt(const std::string& policyName, const std::string& attribute, const int32_t& attributeValue)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << attribute;
        wi << attributeValue;
        call.member("setCPUPolicyInt");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    ::DBus::Struct< std::string, bool, bool, int32_t, bool, int32_t, bool, int32_t > getFeedbackPolicy(const int32_t& policyID)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyID;
        call.member("getFeedbackPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< std::string, bool, bool, int32_t, bool, int32_t, bool, int32_t > argout;
        ri >> argout;
        return argout;
    }

    int32_t setFeedbackPolicyString(const std::string& policyName, const std::string& attribute, const std::string& attributeName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << attribute;
        wi << attributeName;
        call.member("setFeedbackPolicyString");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t setFeedbackPolicyInt(const std::string& policyName, const std::string& attribute, const int32_t& attributeValue)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << attribute;
        wi << attributeValue;
        call.member("setFeedbackPolicyInt");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t createFeedbackPolicy(const std::string& policyName, const int32_t& yellowTemperature, const int32_t& orangeTemperature, const int32_t& redTemperature)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        wi << yellowTemperature;
        wi << orangeTemperature;
        wi << redTemperature;
        call.member("createFeedbackPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t deleteFeedbackPolicy(const std::string& policyName)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << policyName;
        call.member("deleteFeedbackPolicy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t PolicyInitialize()
    {
        ::DBus::CallMessage call;
        call.member("PolicyInitialize");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } } 
#endif //__dbusxx__policy_proxy_h__PROXY_MARSHAL_H
